# Generated by Django 4.2.7 on 2023-12-12 21:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articles",
            options={"verbose_name": "Новость", "verbose_name_plural": "Новости"},
        ),
    ]
