# Generated by Django 4.2.7 on 2023-12-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_alter_articles_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="articles",
            name="text_post",
            field=models.TextField(
                blank=True, null=True, verbose_name="Тестовый текст"
            ),
        ),
    ]
