# Generated by Django 4.2.7 on 2024-03-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_articles_text_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articles",
            name="text_post",
            field=models.TextField(verbose_name="Тестовый текст"),
        ),
    ]
