# Generated by Django 4.2.7 on 2024-03-04 19:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_alter_articles_text_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articles",
            name="text_post",
        ),
    ]
