# Generated by Django 4.2.7 on 2023-12-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tickets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="ФИО")),
                ("number", models.CharField(max_length=50, verbose_name="Номер")),
                ("email", models.CharField(max_length=50, verbose_name="Почта")),
                ("qnt", models.IntegerField(verbose_name="Количество")),
            ],
        ),
    ]
