# Generated by Django 4.2.7 on 2023-12-20 05:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tickets",
            options={"verbose_name": "Билет", "verbose_name_plural": "Билеты"},
        ),
    ]
